# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0002_auto_20170303_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ponente',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventpagespeaker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='eventpagespeaker',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventpagespeaker',
            name='last_name',
        ),
        migrations.AddField(
            model_name='eventpagespeaker',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='eventpagespeaker',
            name='mas_info',
            field=models.URLField(blank=True, verbose_name='URL mas info'),
        ),
        migrations.AddField(
            model_name='eventpagespeaker',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
    ]
