# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0003_auto_20170303_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('atribucion', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('descripcion', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('mas', models.URLField(blank=True, verbose_name='URL mas info')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponentes', to='home.Ponentes')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='page',
        ),
        migrations.RemoveField(
            model_name='ponente',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='ponente',
            name='page',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
        migrations.DeleteModel(
            name='Ponente',
        ),
    ]
