# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:24
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0004_auto_20170303_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='page',
        ),
        migrations.AddField(
            model_name='ponentes',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventpagespeaker',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='home.Ponentes'),
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
