# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170303_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpagespeaker',
            options={},
        ),
    ]
