# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0006_auto_20170303_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('mas_info', models.URLField(blank=True, verbose_name='URL mas info')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordina_mesa', to='home.Ponentes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='EventPageSpeaker',
            new_name='Ponente',
        ),
    ]
