# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170303_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezaPie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=255)),
                ('logo2', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='atribucion',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='ponente',
            old_name='atribucion',
            new_name='biografia',
        ),
        migrations.AlterField(
            model_name='mesa',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador', to='home.Ponentes'),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponentes', to='home.Ponentes'),
        ),
    ]
