# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170304_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='encabezado_pie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EncabezaPie'),
        ),
    ]
