# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0010_homepage_encabezado_pie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encabezado_y_Pie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('logo_dga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.DeleteModel(
            name='EncabezaPie',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='encabezado_pie',
        ),
    ]
