# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_ponentes_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponentes',
            name='titulo',
        ),
    ]
