# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170324_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
    ]
