# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('home', '0020_auto_20170329_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaPresentacion',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('presentacion', wagtail.wagtailcore.fields.RichTextField(help_text='Texto presentación')),
                ('objetivos', wagtail.wagtailcore.fields.RichTextField(help_text='Texto objetivos')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='generica',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading_block', wagtail.wagtailcore.blocks.StructBlock((('encabezado', wagtail.wagtailcore.blocks.CharBlock(classname='title', required=True)), ('nivel', wagtail.wagtailcore.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))))), ('paragraph_block', wagtail.wagtailcore.blocks.StructBlock((('clase', wagtail.wagtailcore.blocks.CharBlock(help_text='Clase del div para la hoja de estilos', required=False)), ('texto', wagtail.wagtailcore.blocks.RichTextBlock(help_text='Texto del bloque'))))), ('image_block', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('attribution', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('block_quote', wagtail.wagtailcore.blocks.StructBlock((('texto', wagtail.wagtailcore.blocks.TextBlock()), ('nombre_autor', wagtail.wagtailcore.blocks.CharBlock(blank=True, label='e.g. Guy Picciotto', required=False))))), ('embed_block', wagtail.wagtailembeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15'))), blank=True, verbose_name='Cuerpo de la página'),
        ),
    ]
