# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('home', '0021_auto_20170330_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInscripciones',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('contenido', wagtail.wagtailcore.fields.RichTextField(help_text='Texto inscripciones')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
