# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('home', '0022_paginainscripciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaPreguntasMesa',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PreguntaMesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255, verbose_name='Pregunta a la mesa')),
                ('quien', models.CharField(max_length=255, verbose_name='¿Quién eres?')),
                ('validada', models.BooleanField(default=False)),
            ],
        ),
    ]
