# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20170509_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginapreguntasmesa',
            name='thanks',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Mensaje agradecimiento'),
        ),
    ]
