# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_pildoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pildora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del micro-taller')),
                ('coordinador', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Coordinador')),
                ('procedencia', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Centro')),
                ('observaciones', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Observaciones')),
                ('email', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='email')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pildoras', to='home.Pildoras')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
