# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_pildora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pildora',
            old_name='coordinador',
            new_name='quien',
        ),
    ]
