# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 06:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20170511_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pildora',
            name='email',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='pildora',
            name='observaciones',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='pildora',
            name='procedencia',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='Centro'),
        ),
        migrations.AlterField(
            model_name='pildora',
            name='quien',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='Coordinador'),
        ),
    ]
