# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_doscolumnas'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitulo',
            field=models.CharField(default='22-23 Septiembre - Zaragoza', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titulo',
            field=models.CharField(default='I Jornadas de INNOVACIÓN METODOLÓGICA EN EDUCACIÓN', max_length=240),
        ),
    ]
