# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170302_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponente',
            name='mas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
