# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170302_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponentes',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Ponente'),
        ),
    ]
