# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('home', '0010_bookpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='page',
        ),
        migrations.RemoveField(
            model_name='ponente',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='ponente',
            name='page',
        ),
        migrations.RemoveField(
            model_name='ponentes',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BookPage',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
