# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0022_paginainscripciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTalleres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nif', models.CharField(max_length=32, verbose_name='NIF')),
                ('centro_educativo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Centro Educativo')),
                ('comunidad_autonoma', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comunidad Autónoma')),
                ('taller1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller1', to='home.Talleres')),
                ('taller2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller2', to='home.Talleres')),
                ('taller3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller3', to='home.Talleres')),
                ('taller4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller4', to='home.Talleres')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
