# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0002_auto_20170429_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariotalleres',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usuariotalleres',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='usuariotalleres',
            name='location',
        ),
        migrations.AddField(
            model_name='usuariotalleres',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Profesor en activo'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='taller1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller1', to='home.Taller', verbose_name='Viernes 1'),
        ),
    ]
