# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0004_auto_20170430_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotalleres',
            name='signos',
            field=models.BooleanField(default=False, verbose_name='¿Necesita intérprete de lengua de signos?'),
        ),
        migrations.AddField(
            model_name='usuariotalleres',
            name='traduccion',
            field=models.BooleanField(default=False, verbose_name='¿Necesita traducción simultánea?'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='apellidos',
            field=models.CharField(max_length=240, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='taller1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller1', related_query_name='taller1', to='home.Taller', verbose_name='Viernes 1'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='taller2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller2', related_query_name='taller2', to='home.Taller', verbose_name='Viernes 2'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='taller3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller3', related_query_name='taller3', to='home.Taller', verbose_name='Viernes 3'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='taller4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller4', related_query_name='taller4', to='home.Taller', verbose_name='Sábado'),
        ),
    ]
