# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistentes', '0005_auto_20170502_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeEspera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=240, verbose_name='Apellidos')),
                ('nif', models.CharField(max_length=32, verbose_name='NIF')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Eres profesor/a en activo?')),
                ('signos', models.BooleanField(default=False, verbose_name='¿Necesitas intérprete de lengua de signos?')),
                ('traduccion', models.BooleanField(default=False, verbose_name='¿Necesitas traducción simultánea?')),
                ('centro_educativo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Centro Educativo')),
                ('comunidad_autonoma', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comunidad Autónoma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='¿Eres profesor/a en activo?'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='signos',
            field=models.BooleanField(default=False, verbose_name='¿Necesitas intérprete de lengua de signos?'),
        ),
        migrations.AlterField(
            model_name='usuariotalleres',
            name='traduccion',
            field=models.BooleanField(default=False, verbose_name='¿Necesitas traducción simultánea?'),
        ),
    ]
