# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0006_auto_20170503_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotalleres',
            name='comunidad_autonoma',
            field=models.CharField(blank=True, choices=[('Andalucía', 'Andalucía'), ('Aragón', 'Aragón'), ('Principado de Asturias', 'Principado de Asturias'), ('Baleares', 'Baleares'), ('Canarias', 'Canarias'), ('Cantabria', 'Cantabria'), ('Castilla-La Mancha', 'Castilla-La Mancha'), ('Castilla y León', 'Castilla y León'), ('Cataluña', 'Cataluña'), ('Extremadura', 'Extremadura'), ('Galicia', 'Galicia'), ('La Rioja', 'La Rioja'), ('Comunidad de Madrid', 'Comunidad de Madrid'), ('Región de Murcia', 'Región de Murcia'), ('Comunidad Foral de Navarra', 'Comunidad Foral de Navarra'), ('País Vasco', 'País Vasco'), ('Comunidad Valenciana', 'Comunidad Valenciana'), ('Ciudades autónomas (Ceuta y Melilla)', 'Ciudades autónomas (Ceuta y Melilla)')], max_length=256, null=True, verbose_name='Comunidad Autónoma'),
        ),
    ]
